# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fairpay Coop.
email: info@fairpay.coop
description: > # this means to ignore newlines until "baseurl:"
  The Fairpay Cooperative is an experiment in building a different kind of enterprise.
  Our mission is to facilitate the lowest cost and most practical payment solutions for social enterprises,
  non-profit organizations, and community focused small businesses.  We are committed to complete transparency of all
  operations and finances and a democratic governance by our work contributors and patrons.  We believe in fair
   exchanges of value, and the generation of profits for society, not shareholders.
baseurl: ""
url: "http://fairpay.coop"
twitter_username: fairpaycoop
github_username:  fairpay-coop

# Build settings
markdown: kramdown
